config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/calculadora/:number1/:number2' , to: 'calculator#home'

get '/calculadora/soma/:number1/:number2', to: 'calculator#sum', as: 'soma'
get '/calculadora/:number1/:number2/subtracao', to: 'calculator#minus', as: 'subtracao'
get '/calculadora/:number1/:number2/divisao', to: 'calculator#division', as: 'divisao'
get '/calculadora/:number1/:number2/multiplicacao', to: 'calculator#multiply', as: 'multiplicacao'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController



    def home
        @number1 = params[:number1].to_i 
        @number2 = params[:number2].to_i 
    end 

  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculator/division.html.erb
<%
      @number1 = params[:number1].to_i
      @number2 = params[:number2].to_i
      @resultado  = @number1 / @number2.to_f
%>

<h2><%= @number1%> ÷ <%= @number2%> = <%= @resultado  %></h2>

app/views/calculator/home.html.erb
<h2>Primeiro número : <%= @number1%></h2>
<h2>Segundo número : <%= @number2%></h2>


<%= link_to "Soma", soma_path %>
<%= link_to "Subtração", subtracao_path %>
<%= link_to "Divisão", divisao_path %>
<%= link_to "Multiplicação", multiplicacao_path %>

app/views/calculator/minus.html.erb
<%
      @number1 = params[:number1].to_i
      @number2 = params[:number2].to_i
      @resultado  = @number1 - @number2 
%>

<h2><%= @number1%> - <%= @number2%> = <%= @resultado  %></h2>

app/views/calculator/multiply.html.erb
<%
      @number1 = params[:number1].to_i
      @number2 = params[:number2].to_i
      @resultado  = @number1 * @number2 
%>

<h2><%= @number1%> x <%= @number2%> = <%= @resultado  %></h2>

app/views/calculator/sum.html.erb
<%
      @number1 = params[:number1].to_i
      @number2 = params[:number2].to_i
      @resultado  = @number1 + @number2 
%>

<h2><%= @number1%> + <%= @number2%> = <%= @resultado  %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Calculadora on Rails</h1>
    <%= yield %>
  </body>
</html>